version: '3.8'

services:
  db:
    container_name: db
    image: postgres:latest
    environment:
      POSTGRES_DB: filemove 
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: adminpass
    ports:
      - "5432:5432" 
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app-network

volumes:
  pgdata:

networks:
  app-network:
    driver: bridge
